spring:
  datasource:
    url: jdbc:mysql://liufang.myds.me:3306/soho?useUnicode=true&characterEncoding=utf-8
    username: soho
    password: soho
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    encoding:
      charset: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
