package work.soho.content.biz.wordpress;

import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import work.soho.content.biz.domain.ContentCategory;
import work.soho.content.biz.domain.ContentComment;
import work.soho.content.biz.domain.ContentExternalMapping;
import work.soho.content.biz.domain.ContentInfo;
import work.soho.content.biz.domain.ContentMedia;
import work.soho.content.biz.domain.ContentTag;
import work.soho.content.biz.domain.ContentTagRelation;
import work.soho.content.biz.service.AdminContentCategoryService;
import work.soho.content.biz.service.AdminContentService;
import work.soho.content.biz.service.ContentCommentService;
import work.soho.content.biz.service.ContentExternalMappingService;
import work.soho.content.biz.service.ContentMediaService;
import work.soho.content.biz.service.ContentTagRelationService;
import work.soho.content.biz.service.ContentTagService;
import work.soho.user.api.dto.UserInfoDto;
import work.soho.user.api.service.UserApiService;

import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * WordPress WXR 导出服务
 */
@Service
public class WordPressWxrExportService {
    private static final DateTimeFormatter WP_DATE = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final DateTimeFormatter PUB_DATE = DateTimeFormatter.RFC_1123_DATE_TIME;

    private final AdminContentService contentService;
    private final AdminContentCategoryService categoryService;
    private final ContentTagService tagService;
    private final ContentTagRelationService tagRelationService;
    private final ContentMediaService mediaService;
    private final ContentCommentService commentService;
    private final ContentExternalMappingService externalMappingService;
    private final UserApiService userApiService;

    public WordPressWxrExportService(AdminContentService contentService,
                                     AdminContentCategoryService categoryService,
                                     ContentTagService tagService,
                                     ContentTagRelationService tagRelationService,
                                     ContentMediaService mediaService,
                                     ContentCommentService commentService,
                                     ContentExternalMappingService externalMappingService,
                                     UserApiService userApiService) {
        this.contentService = contentService;
        this.categoryService = categoryService;
        this.tagService = tagService;
        this.tagRelationService = tagRelationService;
        this.mediaService = mediaService;
        this.commentService = commentService;
        this.externalMappingService = externalMappingService;
        this.userApiService = userApiService;
    }

    public byte[] exportWxr() {
        StringBuilder builder = new StringBuilder(4096);
        LocalDateTime now = LocalDateTime.now();
        String nowGmt = now.atZone(ZoneOffset.UTC).format(WP_DATE);

        builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
        builder.append("<!-- Generated by soho-content-biz -->\n");
        builder.append("<rss version=\"2.0\"\n");
        builder.append(" xmlns:excerpt=\"http://wordpress.org/export/1.2/excerpt/\"\n");
        builder.append(" xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n");
        builder.append(" xmlns:wfw=\"http://wellformedweb.org/CommentAPI/\"\n");
        builder.append(" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n");
        builder.append(" xmlns:wp=\"http://wordpress.org/export/1.2/\"\n");
        builder.append(">\n");
        builder.append("<channel>\n");
        builder.append("  <title>").append(escapeXml("soho-content")).append("</title>\n");
        builder.append("  <link>").append(escapeXml("http://localhost")).append("</link>\n");
        builder.append("  <description></description>\n");
        builder.append("  <pubDate>").append(now.atZone(ZoneId.systemDefault()).format(PUB_DATE)).append("</pubDate>\n");
        builder.append("  <language>zh-Hans</language>\n");
        builder.append("  <wp:wxr_version>1.2</wp:wxr_version>\n");
        builder.append("  <wp:base_site_url>").append(escapeXml("http://localhost")).append("</wp:base_site_url>\n");
        builder.append("  <wp:base_blog_url>").append(escapeXml("http://localhost")).append("</wp:base_blog_url>\n");

        Map<Long, UserInfoDto> userCache = new HashMap<>();
        List<ContentInfo> contents = contentService.list();
        for (ContentInfo content : contents) {
            if (content.getUserId() != null && !userCache.containsKey(content.getUserId())) {
                UserInfoDto user = userApiService.getUserById(content.getUserId());
                if (user != null) {
                    userCache.put(content.getUserId(), user);
                }
            }
        }
        for (UserInfoDto user : userCache.values()) {
            builder.append("  <wp:author>");
            builder.append("<wp:author_id>").append(user.getId()).append("</wp:author_id>");
            builder.append("<wp:author_login><![CDATA[").append(nullToEmpty(user.getUsername())).append("]]></wp:author_login>");
            builder.append("<wp:author_email><![CDATA[").append(nullToEmpty(user.getEmail())).append("]]></wp:author_email>");
            builder.append("<wp:author_display_name><![CDATA[").append(nullToEmpty(user.getUsername())).append("]]></wp:author_display_name>");
            builder.append("<wp:author_first_name><![CDATA[]]></wp:author_first_name>");
            builder.append("<wp:author_last_name><![CDATA[]]></wp:author_last_name>");
            builder.append("</wp:author>\n");
        }

        Map<Long, ContentCategory> categoryCache = new HashMap<>();
        for (ContentCategory category : categoryService.list()) {
            categoryCache.put(category.getId(), category);
        }

        List<ContentMedia> mediaList = mediaService.list();
        for (ContentMedia media : mediaList) {
            appendAttachmentItem(builder, media, nowGmt);
        }

        for (ContentInfo content : contents) {
            appendContentItem(builder, content, categoryCache, nowGmt);
        }

        builder.append("</channel>\n");
        builder.append("</rss>\n");
        return builder.toString().getBytes(StandardCharsets.UTF_8);
    }

    private void appendContentItem(StringBuilder builder,
                                   ContentInfo content,
                                   Map<Long, ContentCategory> categoryCache,
                                   String nowGmt) {
        ContentExternalMapping mapping = externalMappingService.lambdaQuery()
                .eq(ContentExternalMapping::getContentId, content.getId())
                .last("limit 1")
                .one();

        String status = resolveStatus(content, mapping);
        String type = resolveType(mapping);
        String slug = resolveSlug(content.getTitle(), mapping);
        Long postId = resolvePostId(content, mapping);
        String postDate = formatDate(content.getCreatedTime());
        String postDateGmt = formatDateGmt(content.getCreatedTime(), nowGmt);

        builder.append("  <item>\n");
        builder.append("    <title>").append(cdata(content.getTitle())).append("</title>\n");
        builder.append("    <link>").append(escapeXml("http://localhost/?p=" + postId)).append("</link>\n");
        builder.append("    <pubDate>").append(formatPubDate(content.getCreatedTime())).append("</pubDate>\n");
        builder.append("    <dc:creator><![CDATA[").append(resolveAuthor(content)).append("]]></dc:creator>\n");
        builder.append("    <guid isPermaLink=\"false\">").append(escapeXml("http://localhost/?p=" + postId)).append("</guid>\n");
        builder.append("    <description></description>\n");
        builder.append("    <content:encoded>").append(cdata(content.getBody())).append("</content:encoded>\n");
        builder.append("    <excerpt:encoded>").append(cdata(content.getDescription())).append("</excerpt:encoded>\n");
        builder.append("    <wp:post_id>").append(postId).append("</wp:post_id>\n");
        builder.append("    <wp:post_date>").append(postDate).append("</wp:post_date>\n");
        builder.append("    <wp:post_date_gmt>").append(postDateGmt).append("</wp:post_date_gmt>\n");
        builder.append("    <wp:comment_status>").append(nullToEmpty(mapping == null ? null : mapping.getExternalCommentStatus())).append("</wp:comment_status>\n");
        builder.append("    <wp:ping_status>").append(nullToEmpty(mapping == null ? null : mapping.getExternalPingStatus())).append("</wp:ping_status>\n");
        builder.append("    <wp:post_name>").append(escapeXml(slug)).append("</wp:post_name>\n");
        builder.append("    <wp:status>").append(escapeXml(status)).append("</wp:status>\n");
        builder.append("    <wp:post_parent>").append(mapping == null || mapping.getExternalParentId() == null ? 0 : mapping.getExternalParentId()).append("</wp:post_parent>\n");
        builder.append("    <wp:menu_order>").append(mapping == null || mapping.getExternalMenuOrder() == null ? 0 : mapping.getExternalMenuOrder()).append("</wp:menu_order>\n");
        builder.append("    <wp:post_type>").append(escapeXml(type)).append("</wp:post_type>\n");
        builder.append("    <wp:post_password>").append(escapeXml(nullToEmpty(mapping == null ? null : mapping.getExternalPassword()))).append("</wp:post_password>\n");

        if (content.getCategoryId() != null) {
            ContentCategory category = categoryCache.get(content.getCategoryId());
            if (category != null) {
                String catSlug = slugify(StringUtils.hasText(category.getKeyword()) ? category.getKeyword() : category.getName());
                builder.append("    <category domain=\"category\" nicename=\"").append(escapeXml(catSlug)).append("\">");
                builder.append(cdata(category.getName())).append("</category>\n");
            }
        }

        List<ContentTagRelation> relations = tagRelationService.lambdaQuery()
                .eq(ContentTagRelation::getContentId, content.getId())
                .list();
        for (ContentTagRelation relation : relations) {
            ContentTag tag = tagService.getById(relation.getTagId());
            if (tag == null) {
                continue;
            }
            String tagSlug = slugify(StringUtils.hasText(tag.getSlug()) ? tag.getSlug() : tag.getName());
            builder.append("    <category domain=\"post_tag\" nicename=\"").append(escapeXml(tagSlug)).append("\">");
            builder.append(cdata(tag.getName())).append("</category>\n");
        }

        List<ContentComment> comments = commentService.lambdaQuery()
                .eq(ContentComment::getContentId, content.getId())
                .list();
        for (ContentComment comment : comments) {
            appendComment(builder, comment, nowGmt);
        }

        builder.append("  </item>\n");
    }

    private void appendAttachmentItem(StringBuilder builder, ContentMedia media, String nowGmt) {
        Long postId = media.getExternalMediaId() != null ? media.getExternalMediaId() : media.getId();
        String title = StringUtils.hasText(media.getTitle()) ? media.getTitle() : "attachment";

        builder.append("  <item>\n");
        builder.append("    <title>").append(cdata(title)).append("</title>\n");
        builder.append("    <link>").append(escapeXml(media.getUrl())).append("</link>\n");
        builder.append("    <pubDate>").append(formatPubDate(media.getCreatedTime())).append("</pubDate>\n");
        builder.append("    <dc:creator><![CDATA[").append("system").append("]]></dc:creator>\n");
        builder.append("    <guid isPermaLink=\"false\">").append(escapeXml(media.getUrl())).append("</guid>\n");
        builder.append("    <description></description>\n");
        builder.append("    <content:encoded>").append(cdata(media.getDescription())).append("</content:encoded>\n");
        builder.append("    <wp:post_id>").append(postId).append("</wp:post_id>\n");
        builder.append("    <wp:post_date>").append(formatDate(media.getCreatedTime())).append("</wp:post_date>\n");
        builder.append("    <wp:post_date_gmt>").append(formatDateGmt(media.getCreatedTime(), nowGmt)).append("</wp:post_date_gmt>\n");
        builder.append("    <wp:post_name>").append(escapeXml(slugify(title))).append("</wp:post_name>\n");
        builder.append("    <wp:status>inherit</wp:status>\n");
        builder.append("    <wp:post_parent>0</wp:post_parent>\n");
        builder.append("    <wp:menu_order>0</wp:menu_order>\n");
        builder.append("    <wp:post_type>attachment</wp:post_type>\n");
        builder.append("    <wp:post_password></wp:post_password>\n");
        builder.append("    <wp:post_mime_type>").append(escapeXml(nullToEmpty(media.getMimeType()))).append("</wp:post_mime_type>\n");
        builder.append("    <wp:attachment_url>").append(escapeXml(nullToEmpty(media.getUrl()))).append("</wp:attachment_url>\n");
        builder.append("  </item>\n");
    }

    private void appendComment(StringBuilder builder, ContentComment comment, String nowGmt) {
        Long commentId = comment.getExternalCommentId() != null ? comment.getExternalCommentId() : comment.getId();
        builder.append("    <wp:comment>\n");
        builder.append("      <wp:comment_id>").append(commentId).append("</wp:comment_id>\n");
        builder.append("      <wp:comment_author>").append(cdata(nullToEmpty(comment.getAuthorName()))).append("</wp:comment_author>\n");
        builder.append("      <wp:comment_author_email>").append(cdata(nullToEmpty(comment.getAuthorEmail()))).append("</wp:comment_author_email>\n");
        builder.append("      <wp:comment_author_url>").append(cdata(nullToEmpty(comment.getAuthorUrl()))).append("</wp:comment_author_url>\n");
        builder.append("      <wp:comment_date>").append(formatDate(comment.getCreatedTime())).append("</wp:comment_date>\n");
        builder.append("      <wp:comment_date_gmt>").append(formatDateGmt(comment.getCreatedTime(), nowGmt)).append("</wp:comment_date_gmt>\n");
        builder.append("      <wp:comment_content>").append(cdata(nullToEmpty(comment.getContent()))).append("</wp:comment_content>\n");
        builder.append("      <wp:comment_approved>").append(escapeXml(nullToEmpty(comment.getStatus()))).append("</wp:comment_approved>\n");
        builder.append("      <wp:comment_parent>").append(comment.getParentId() == null ? 0 : comment.getParentId()).append("</wp:comment_parent>\n");
        builder.append("      <wp:comment_user_id>").append(comment.getUserId() == null ? 0 : comment.getUserId()).append("</wp:comment_user_id>\n");
        builder.append("    </wp:comment>\n");
    }

    private String resolveAuthor(ContentInfo content) {
        if (content.getUserId() == null) {
            return "system";
        }
        UserInfoDto user = userApiService.getUserById(content.getUserId());
        if (user == null || !StringUtils.hasText(user.getUsername())) {
            return "system";
        }
        return user.getUsername();
    }

    private String resolveSlug(String title, ContentExternalMapping mapping) {
        if (mapping != null && StringUtils.hasText(mapping.getExternalSlug())) {
            return mapping.getExternalSlug();
        }
        return slugify(title);
    }

    private String resolveStatus(ContentInfo content, ContentExternalMapping mapping) {
        if (mapping != null && StringUtils.hasText(mapping.getExternalStatus())) {
            return mapping.getExternalStatus();
        }
        if (content.getStatus() == null || content.getStatus() == 0) {
            return "draft";
        }
        return "publish";
    }

    private String resolveType(ContentExternalMapping mapping) {
        if (mapping != null && StringUtils.hasText(mapping.getExternalType())) {
            return mapping.getExternalType();
        }
        return "post";
    }

    private Long resolvePostId(ContentInfo content, ContentExternalMapping mapping) {
        if (mapping != null && mapping.getExternalObjectId() != null) {
            return mapping.getExternalObjectId();
        }
        return content.getId();
    }

    private String formatDate(LocalDateTime time) {
        if (time == null) {
            return "";
        }
        return time.format(WP_DATE);
    }

    private String formatDateGmt(LocalDateTime time, String fallback) {
        if (time == null) {
            return fallback;
        }
        return time.atZone(ZoneOffset.UTC).format(WP_DATE);
    }

    private String formatPubDate(LocalDateTime time) {
        LocalDateTime actual = time == null ? LocalDateTime.now() : time;
        return actual.atZone(ZoneId.systemDefault()).format(PUB_DATE);
    }

    private static String escapeXml(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&apos;");
    }

    private static String cdata(String value) {
        String safe = value == null ? "" : value;
        return "<![CDATA[" + safe.replace("]]>", "]]]]><![CDATA[>") + "]]>";
    }

    private static String nullToEmpty(String value) {
        return value == null ? "" : value;
    }

    private static String slugify(String text) {
        if (!StringUtils.hasText(text)) {
            return "";
        }
        String lower = text.trim().toLowerCase();
        StringBuilder builder = new StringBuilder();
        boolean dash = false;
        for (int i = 0; i < lower.length(); i++) {
            char ch = lower.charAt(i);
            if (Character.isLetterOrDigit(ch)) {
                builder.append(ch);
                dash = false;
            } else {
                if (!dash) {
                    builder.append('-');
                    dash = true;
                }
            }
        }
        String slug = builder.toString();
        while (slug.startsWith("-")) {
            slug = slug.substring(1);
        }
        while (slug.endsWith("-")) {
            slug = slug.substring(0, slug.length() - 1);
        }
        return slug;
    }
}
