

upload:
  enable: true
  defaultChannel: oss
  channels:
    oss:
      enable: true
      type: oss
      config:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        accessKeyId: LTAI5t94HpzenYDMRKHAnAF8
        accessKeySecret: peGhHVTr6CI163HUr3AlwvcDuBNhA4
        bucketName: igogo-test
        urlPrefix: https://igogo-test.oss-cn-shenzhen.aliyuncs.com/
    cos:
      type: cos
      enable: true
      config:
        secretId: AKIDnPlrgEVWGkywd3C3ey1mHVR6VcSMzNUk
        secretKey: 4sQgfNoztWt0qPikVzC8nBI9j12nHUQ5
        region: ap-guangzhou
        bucketName: soho-admin-demo-1258009624
        urlPrefix: https://soho-admin-demo-1258009624.file.myqcloud.com/
    cos2:
      type: cos
      enable: true
      config:
        secretId: AKIDnPlrgEVWGkywd3C3ey1mHVR6VcSMzNUk
        secretKey: 4sQgfNoztWt0qPikVzC8nBI9j12nHUQ5
        region: ap-guangzhou
        bucketName: soho-admin-demo-1258009624
        urlPrefix: https://soho-admin-demo-1258009624.file.myqcloud.com/

    qiniu:
      type: qiniu
      enable: true
      config:
        accessKey: IfuIJ_vOjbTs0UfH9A7SPUAz8cNZf_jZ_8D2qs8U
        secretKey: ZFXR8eXxScaFvgTyMU500P5oWmd0PHlJjwKtfERG
        bucket: soho-demo
        urlPrefix: http://ra86b7o3s.hn-bkt.clouddn.com/

    file:
      type: file
      enable: true
      config:
        baseDir: D:\data\
        urlPrefix: http://ra86b7o3s.hn-bkt.clouddn.com/

springfox:
  documentation:
    open-api:
      enabled: true
    swagger-ui:
      enabled: true
      base-url: /api-docs

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

#   redis://127.0.0.1:7181
redisson:
  nodeAddress: redis://127.0.0.1:6379

sms:
  enable: true
  defaultChannel: aliyun
  channels:
    aliyun:
      enable: true
      type: aliyun
      config:
        endpoint: dysmsapi.aliyuncs.com
        accessKeyId: LTAI5t94HpzenYDMRKHAnAF8
        accessKeySecret: peGhHVTr6CI163HUr3AlwvcDuBNhA4
    tencent:
      type: tencent
      config:
        secretId: AKIDnPlrgEVWGkywd3C3ey1mHVR6VcSMzNUk
        secretKey: 4sQgfNoztWt0qPikVzC8nBI9j12nHUQ5
        region: ap-guangzhou
        endpoint: sms.tencentcloudapi.com
        sdkAppid: 1400673508
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl